server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  zipkin:
    base-url: http://localhost:9411  # URL donde corre Zipkin
    enabled: true
    sender:
      type: WEB  # usa HTTP para enviar las trazas
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0  # 100% de las solicitudes serán trazadas (útil en desarrollo)
  endpoints:
    web:
      exposure:
        include: "*"